# This is a basic workflow to help you get started with Actions

name: Sort

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  schedule: 
    - cron: '30 07 * * 05'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-stable:
    runs-on: ubuntu-latest
    steps: 
    - name: Sort Themes
      run: |
        whoami
        sudo apt install -y git findutils sudo
        git clone https://github.com/Osmium-Linux/rtl88-Themes-sorted
        cd rtl88-Themes-sorted
        sudo chmod +x ./sort.sh
        ./sort.sh
        
