# This is a basic workflow to help you get started with Actions

name: Sort

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  schedule: 
    - cron: '30 07 * * 05'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-stable:
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.github_token }}
    steps: 
    - name: Sort Themes
      run: |
        #wget https://github.com/apache/flink/raw/master/tools/azure-pipelines/free_disk_space.sh
        #chmod +x free_disk_space.sh
        #sh free_disk_space.sh
        #rm -rf "/usr/local/share/boost"
        #rm -rf "$AGENT_TOOLSDIRECTORY"
        #sudo apt clean
        set -x
        #whoami
        sudo apt install -y git findutils sudo
        git clone https://github.com/Osmium-Linux/rtl88-Themes-sorted
        cd rtl88-Themes-sorted
        rm -rf output
        mkdir -p ./output/
        sudo chmod +x ./sort.sh
        ./sort.sh
        git config user.email "tysayahi@gmail.com"
        git config user.name "Eile Kerning"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git checkout main
        git add .
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin main)

